#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG=/usr/bin/udp2raw

start_service() {
	if [ "$(uci get udp2raw.global.enabled)" != "1" ]; then
		echo "udp2raw service is disabled."
		return 1
	fi

	local default_log_level=$(uci get udp2raw.global.default_log_level)
	[ -z "$default_log_level" ] && default_log_level=4

	config_load udp2raw
	config_foreach start_instance instance $default_log_level
}

start_instance() {
	local default_log_level=$1
	local name mode listen_ip listen_port remote_ip remote_port key raw_mode log_level

	config_get name "$1" name
	config_get mode "$1" mode
	config_get listen_ip "$1" listen_ip
	config_get listen_port "$1" listen_port
	config_get remote_ip "$1" remote_ip
	config_get remote_port "$1" remote_port
	config_get key "$1" key
	config_get raw_mode "$1" raw_mode
	config_get log_level "$1" log_level

	[ -z "$name" -o -z "$listen_port" -o -z "$remote_ip" -o -z "$remote_port" -o -z "$key" -o -z "$raw_mode" ] && {
		echo "Skipping incomplete instance configuration."
		return
	}

	[ -z "$log_level" ] && log_level=$default_log_level

	procd_open_instance "$name"
	procd_set_param command $PROG \
		$(if [ "$mode" = "server" ]; then echo "-s"; else echo "-c"; fi) \
		-l "$listen_ip:$listen_port" \
		-r "$remote_ip:$remote_port" \
		-k "$key" \
		--raw-mode "$raw_mode" \
		--log-level "$log_level"
	procd_set_param respawn
	procd_close_instance
}

stop_service() {
	procd_kill $PROG
}
