name: Build OpenWRT Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git \
        libncurses-dev libssl-dev rsync unzip zlib1g-dev file wget

    - name: Download OpenWRT SDK
      run: |
        wget https://downloads.openwrt.org/releases/24.10.0/targets/mediatek/mt7622/openwrt-sdk-24.10.0-mediatek-mt7622_gcc-13.3.0_musl.Linux-x86_64.tar.zst
        tar -I zstd -xf openwrt-sdk-24.10.0-mediatek-mt7622_gcc-13.3.0_musl.Linux-x86_64.tar.zst
        mv openwrt-sdk-24.10.0-mediatek-mt7622_gcc-13.3.0_musl.Linux-x86_64 sdk

    - name: Prepare custom package
      run: |
        mkdir -p sdk/package/custom/udp2raw
        cp -r $(ls -A) sdk/package/custom/udp2raw


    - name: Update feeds
      working-directory: sdk
      run: |
        ./scripts/feeds update -a || true
        ./scripts/feeds install -a || true

    - name: Build IPK
      working-directory: sdk
      run: |
        make defconfig
        make package/custom/udp2raw/compile V=s

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: udp2raw-ipk
        path: sdk/bin/packages/*/*/*.ipk
